apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: network-demo
spec:
  podSelector:
    matchLabels:
      app: "db"
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              dbAccess: "true"
      ports:
        - protocol: TCP
          port: 5432
