apiVersion: v1
kind: Pod
metadata:
  name: db
  namespace: network-demo
  labels:
    name: db
    app: db
spec:
  containers:
    - name: postgres
      image: bitnami/postgresql:12.12.0
      env:
        - name: POSTGRESQL_PASSWORD
          value: my-secret-password
        - name: POSTGRESQL_DATABASE
          value: test
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
      ports:
        - containerPort: 5432
